config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :wines
  devise_for :users
  root 'pages#home'

  get 'dashboard' => "pages#dashboard"

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      can :read, :all
      can :manage, Wine do |wine|
       wine.try(:user) == user

      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  before_create :populate_guid
  belongs_to    :wine

  include AASM
  aasm column: 'state' do
    state :pending, initial: true
    state :processing
    state :finished
    state :errored

    event :process, after: :charge_card do
      transitions from: :pending, to: :processing
    end

    event :finish do
      transitions from: :processing, to: :finished
    end

    event :fail do
      transitions from: :processing, to: :errored
    end
  end

  def charge_card
    begin
      save!
      charge = Stripe::Charge.create(
        amount: self.amount,
        currency: "usd",
        card: self.stripe_token,
        description: "Wine Sale"
        )
      self.update(stripe_id: charge.id)
      self.finish!
    rescue Stripe::StripeError => e
      self.update_attributes(error: e.message)
      self.fail!
    end
  end

  private

  def populate_guid
     self.guid = SecureRandom.uuid()
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  def search_wines

   wines = Wine.all

   wines = wines.where("name like ?", "%#{keywords}%") if keywords.present?
   wines = wines.where("category like ?", category) if category.present?
   wines = wines.where("price >= ?", min_price) if min_price.present?
   wines = wines.where("price <= ?", max_price) if max_price.present?

   return wines
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :wines
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  def self.search(search)
  if search
    where(['name LIKE ?', "%#{search}%"])
  else
    all
  end
end

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_attached_file :image
  has_many :sales

  validates_attachment_content_type :image,
  content_type:  /^image\/(png|gif|jpeg)/,
  message: "Only images allowed"

  validates :image, attachment_presence: true

  validates_numericality_of :price,
  greater_than: 49, message: "Must be at least 50 cents"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :store_location

  def store_location
  # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get?
    if (request.path != "/users/sign_in" &&
      request.path != "/users/sign_up" &&
      request.path != "/users/password/new" &&
      request.path != "/users/password/edit" &&
      request.path != "/users/confirmation" &&
      request.path != "/users/sign_out" &&
      !request.xhr?) # don't store ajax calls
    session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
  session[:previous_url] || root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
 	  redirect_to root_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def home
    if current_user
      redirect_to wines_path
    end
  end

  def dashboard
    @wines = current_user.wines
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  @search = Search.new
  @categories = Wine.uniq.pluck(:category)
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private
  def search_params
   params.require(:search).permit(:keywords, :category, :min_price, :max_price)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def create
    wine = Wine.find_by!(slug: params[:slug])
    sale = wine.sales.create(
      amount: wine.price,
      buyer_email: current_user.email,
      seller_email: wine.user.email,
      stripe_token: params[:stripeToken])
  sale.process!
  if sale.finished?
    redirect_to pickup_url(guid: sale.guid), notice: "Transaction Successful"
  else
    redirect_to wine_path(wine), notice: "Something went wrong"
  end
end

  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @wine = @sale.wine
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  def index
    @wines = Wine.search(params[:search])
  end

  def show
  end

  def new
    @wine = Wine.new
  end

  def edit
    authorize! :manage, @wine
  end

  def create
    @wine = current_user.wines.new(wine_params)

      if @wine.save
        redirect_to @wine, notice: 'Wine was successfully created.'
      else
        render :new
      end
  end

  def update
    authorize! :manage, @wine
      if @wine.update(wine_params)
        redirect_to @wine, notice: 'Wine was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    authorize! :manage, @wine

    @wine.destroy
      redirect_to wines_path, notice: 'Wine was successfully destroyed.'
  end


  private
    def set_wine
      @wine = Wine.friendly.find(params[:id])
    end

    def wine_params
      params.require(:wine).permit(:name, :description, :price, :availability, :image, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wine Run", root_path, class: "navbar-brand" %>
    </div>
    <% if current_user.present? %>
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
          <%= form_tag wines_path, :method => 'get' do %>
          <% end %>
          <%= link_to "Advanced Search", new_search_path %>

        </div>
        <% end %>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
      <!-- <li><%= link_to "Shop Wines", wines_path %></li> -->

      <% if current_user %>

      <li><%= link_to "Settings", edit_user_registration_path %></li>
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

      <% else %>

        <li><%= link_to "Sign In", new_user_session_path %></li>

      <% end %>

      <li>

      </li>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WineRun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="assets/favicon.ico">

 -->
  <!-- Bootstrap core CSS -->
  <link href="assets/css/bootstrap.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="assets/css/ionicons.min.css" rel="stylesheet">
  <link href="assets/css/style.css" rel="stylesheet">


  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="assets/js/ie10-viewport-bug-workaround.js"></script>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <%= render "layouts/header" %>
<!-- <div class="container"> -->
  <% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
  <button class="close" data-dismiss="alert">x</button>
  <%= message %>
  </div>
  <% end %>
<%= yield %>
<!-- </div> -->

<!-- <script src="assets/js/jquery.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/retina-1.1.0.js"></script> -->

</body>
</html>

app/views/pages/_purchased.html.erb
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @purchased.each do |sale| %>
    <tr>
      <td><%= link_to sale.wine.name, pickup_path(sale.guid) %></td>
      <td><%= time_ago_in_words(sale.created_at) %> ago</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/_sales.html.erb
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Buyer</th>
      </tr>
    </thead>
    <tbody>
      <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.wine.name, pickup_path(sale.guid) %></td>
        <td><%= time_ago_in_words(sale.created_at) %> ago</td>
        <td><%= sale.buyer_email %></td>
      </tr>
      <% end %>
    </tbody>
</table>

app/views/pages/_wines.html.erb
<table class="table table-condensed">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Available</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.id %></td>
        <td><%= link_to wine.name, wine_path(wine) %></td>
        <td><%= wine.availability %></td>
        <td><%= link_to "Edit", edit_wine_path(wine) %></td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
  <h1 class="text-center">Dashboard</h1>
    <div class="text-center">
    <%= link_to "New Wine", new_wine_path, class: "btn btn-primary btn-sm" %></div>
  <div class="clearfix"></div>
    <div class="col-md-4">
    <div class="dash-box">
      <h3 class="white uppercase">
      Wines
      </h3>
    </div>
      <%= render "wines" %>
    </div>
    <div class="col-md-4">
      <div class="dash-box">
      <h3 class="white uppercase">
      Purchased
    </h3>
    </div>
    <%= render "purchased" %>
  </div>
  <div class="col-md-4">
    <div class="dash-box">
      <h3 class="white uppercase">
    Sales
    </h3>
  </div>
    <%= render "sales" %>
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="assets/favicon.ico"> -->

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/css/ionicons.min.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="assets/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div id="h">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2 centered">
            <h1>Your Favorite Bottle Of Wine Delivered<br/>In Less Than An Hour.</h1>
              <a class="btn btn-conf btn-green" href="/wines" role="button">Shop Wines Now</a>
            </div><!--/mt-->
          </div>
        </div><!--/row-->
      </div><!--/container-->
    </div><!-- /H -->

    <div class="container ptb">
      <div class="row centered">
        <div class="col-md-12">
          <h2>Anytime, Anywhere.<br> Order from your smartphone, tablet or laptop.</h2>
        </div>
        <!-- <div class="col-md-6"> -->
          <img src="assets/placeit.png" class="img-responsive mt" alt="">
        <!-- </div> -->
      </div><!--/row-->
    </div><!--/container-->
    <div id="sep">
      <div class="container">
        <div class="row centered">
          <div class="col-md-8 col-md-offset-2">
            <h1>Bring the dinner party home and spend more times with friends. Let us take care of the rest.</h1>
          </div><!--/col-md-8-->
        </div>
      </div>
    </div><!--/sep-->
  <div class="container">
    <div class="text-center">
  <!-- <div class="module light" id="module-fast-free-easy"> -->
      <!-- <div class="row"> -->
        <!-- <div class="large-4 medium-4 columns center divider-r"> -->
          <h3 class="heading-thin">Browse</h3>
          <h4 class="subhead-thin">Discover the best selection of wine.</h4>
      <!-- </div> -->
    <!-- <div class="large-4 medium-4 columns center divider-r"> -->
          <h3 class="heading-thin">Order</h3>
          <h4 class="subhead-thin">Find what you want in a few quick<br>clicks. No hidden costs.</h4>
    <!-- </div> -->
    <!-- <div class="large-4 medium-4 columns center"> -->
          <h3 class="heading-thin">Enjoy</h3>
          <h4 class="subhead-thin">Delivered to your door in<br>around 30-60 minutes.</h4>
    </div>
  <!-- </div> -->
<!-- </div> -->
</div>
    <div id="g">
      <div class="container">
        <div class="row sponsor centered">
          <div class="col-sm-2 col-sm-offset-1">
            <img src="assets/ironyard.png" alt="">
          </div>
          <div class="col-sm-2">
            <img src="assets/ironyard.png" alt="">
          </div>
          <div class="col-sm-2">
            <img src="assets/ironyard.png" alt="">
          </div>
          <div class="col-sm-2">
            <img src="assets/ironyard.png" alt="">
          </div>
          <div class="col-sm-2">
            <img src="assets/ironyard.png" alt="">
          </div>
        </div><!--/row-->
      </div>
    </div><!--/g-->

    <div id="green">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 centered">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                <div class="item active">
                  <h3>Wine Run is one of the best things to ever happen to Houston!</h3>
                  <h5><tgr>DAVID JHONSON</tgr></h5>
                </div>
                <div class="item">
                  <h3>It is about time that something like this has happened. I'm never going to the store again.</h3>
                  <h5><tgr>MARK LAWRENCE</tgr></h5>
                </div>
                <div class="item">
                  <h3>Wine delivered like Pizza!!! This is awesome sauce!!.</h3>
                  <h5><tgr>LISA SMITH</tgr></h5>
                </div>
              </div>
            </div><!--/Carousel-->

          </div>
        </div><!--/row-->
      </div><!--/container-->
    </div><!--/green-->

    <div id="f">
      <div class="container">
        <div class="row centered">
          <h2>Contact Us</h2>
          <h5>HELLO@WINERUN.COM</h5>

          <p class="mt">
          </p>
          <h6 class="mt">COPYRIGHT 2015 - WINE RUN</h6>
        </div><!--/row-->
      </div><!--/container-->
    </div><!--/F-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/retina-1.1.0.js"></script>
  </body>
</html>

app/views/searches/new.html.erb
<div class="text-center">
<h1>Advanced Search</h1>

<%= form_for @search do |s| %><br/>
  <div class="field">
    <%= s.label :keywords %><br />
    <%= s.text_field :keywords %>
  </div><br/>
  <div class="field">
    <%= s.label :category_id %><br />
    <%= s.select :category, options_for_select(@categories), :include_blank => true %>
  </div><br/>
  <div class="field">
    <%= s.label :min_price, "Price Range" %><br />
    <%= s.text_field :min_price, size: 10 %> -
    <%= s.text_field :max_price, size: 10 %>
  </div><br/>
  <div class="actions">
  <%= s.submit "Search", class: "btn btn-primary" %>
  </div>
</div>

<% end %>

app/views/searches/show.html.erb
<h1>Search Results</h1>
<% if @search.search_wines.empty? %>
	<p>No Records Found</p>
<% else %>
	<% @search.search_wines.each do |c| %>
		<div>
			<h3><%= c.name %></h3>
			<p>Price: $<%= c.price %></p>
			<p>Category: <%= c.category %></p>
		</div>
	<% end %>
<% end %>

app/views/transactions/pickup.html.erb
<div class="row text-center">
<h1>WOOHOO Your Order Is Complete.</h1><br/>
<h5>Here is your order #: <%= @sale.guid %></h5><br/>
 <h4>We Shall Be Arriving With Your Favorite Wine In Less Than An Hour!<h4><br/>
   <h4>CHEERS!</h4><br/>
     <div class="row">
         <div class="col-xs-12 col-sm-offset-3 col-sm-6">
             <div class="panel panel-default">
                 <div class="panel-heading c-list">
                     <span class="title">Your Designated Driver For Today</span>
                 </div>

                 <div class="row" style="display: none;">
                     <div class="col-xs-12">
                         <div class="input-group c-search">
                             <input type="text" class="form-control" id="contact-list-search">
                             <span class="input-group-btn">
                                 <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search text-muted"></span></button>
                             </span>
                         </div>
                     </div>
                 </div>

                 <ul class="list-group" id="contact-list">
                     <li class="list-group-item">
                         <div class="col-xs-12 col-sm-3">
                             <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="Scott Stevens" class="img-responsive img-circle" />
                         </div>
                         <div class="col-xs-12 col-sm-9">
                             <span class="name">Scott Stevens</span><br/>
                             <span class="visible-xs"> <span class="text-muted">(870) 288-4149</span><br/></span>
                             <span class="fa fa-comments text-muted c-info" data-toggle="tooltip" title="Text Me If You Have Questions"></span>
                             <span class="visible-xs"> <span class="text-muted">(870) 288-4149</span><br/></span>
                         </div>

                         <div class="clearfix"></div>
                     </li>
                 </ul>
             </div>
         </div>
 	</div>

     <div id="cant-do-all-the-work-for-you" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
         <div class="modal-dialog modal-sm">
             <div class="modal-content">
                 <div class="modal-header">
                     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                     <h4 class="modal-title" id="mySmallModalLabel">Ooops!!!</h4>
                 </div>
                 <div class="modal-body">
                     <p>I am being lazy and do not want to program an "Add User" section into this snippet... So it looks like you'll have to do that for yourself.</p><br/>
                     <p><strong>Sorry<br/>
                     ~ Mouse0270</strong></p>
                 </div>
             </div>
         </div>
     </div>

     <!-- JavaScrip Search Plugin -->
     <script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>

 </div>

app/views/wines/_form.html.erb
<%= simple_form_for(@wine, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>


    <%= f.input :name, required: true, label: false, placeholder: "Wine Name", input_html: {class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "Description", input_html: {class: "form-control", rows: 5} %>
    <%= f.input :price, required: true, label: false, placeholder: "Price", input_html: {class: "form-control"} %>
    <%= f.input :image %>
    <%= f.input :category, required: true, label: false, placeholder: "Category", input_html: {class: "form-control"} %>
    <%= f.input :availability, required: false %>

    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/wines/_wine.html.erb
<div class="col-md-3">
<div class="thumbnail">
<%= link_to wine_path(wine) do %>
<%= image_tag wine.image.url(:original), class: "img-responsive" %>
<% end %>

<div class="caption">
<p><strong><%= link_to wine.name, wine_path(wine) %></strong></p>
<p>$<%= wine.price.to_f / 100 %></p>
</div>
</div>
</div>

app/views/wines/edit.html.erb
<h1 class="text-center">Editing Wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<div class="container">
<div class="row">


<% @wines.in_groups_of(4, false) do |wines| %>
  <div class="row">
    <% wines.each do |wine| %>
      <%= render wine %>
    <% end %>
  </div>
<% end %>

</div>
</div>

app/views/wines/new.html.erb
<h1 class="text-center">New Wine</h1>

<%= render 'form' %>

<div class="text-center"><%= link_to 'Back', wines_path %>
</div>

app/views/wines/show.html.erb
<div class="container">
<div class="row">

<div class="col-md-6">
<%= image_tag @wine.image.url(:original), class: "img-responsive" %>
</div>

<div class="col-md-6">
<h3><%= @wine.name %></h3>
<p class="justify"><%= @wine.description %></p>
<h4>$<%= @wine.price.to_f / 100 %></h4>

<% if current_user %>
<%= form_tag buy_path(slug: @wine.slug) do %>
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-amount="<%= @wine.price %>"
  data-name="Wine Run"
  data-description="<%= @wine.name %>"
  data-email="<%= current_user.email %>">
</script>
<% end %>
<% else %>
<h4><%= link_to "Proceed to checkout", new_user_session_path %></h4>
<% end %>

</div>

</div>
</div>

<div class="text-center">
  <% if current_user %>
<%= link_to "Edit", edit_wine_path(@wine)  %>
<%= link_to "Back", wines_path  %>
<% end %>
</div>